### ISSUE TITLE
Rust Language Server: Failed to start language server

### ISSUE THREAD

**Issue by atomrc** [ul/kak-lsp#101]
Hi guys,

I am trying to setup `rls` but, for some reason, the server won't start.

In debug mode, I get this error in the log

```
session = "384"
client  = ""
buffile = "/home/atomrc/Workspace/synchee/src/main.rs"
version = 1
method  = "textDocument/didOpen"
[params]
, module: kak_lsp::editor_transport:180
Oct 10 22:56:18.481 DEBG Routing editor request to Route { session: "384", language: "rust", root: "/home/atomrc/Workspace/synchee" }, module: kak_lsp::controller:76
Oct 10 22:56:18.481 INFO Starting Language server `rls `, module: kak_lsp::language_server_transport:16
thread '<unnamed>' panicked at 'Failed to start language server: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Any idea what I could do wrong?
I am on a fresh install of rust (using rustup).

Thanks for your help.

**Comment by ul** [comment]
Hello! Just to double-check, have you installed RLS via `rustup component add rls-preview rust-analysis rust-src`? Because Rust comes without RLS by default and kak-lsp doesn't manage RLS installation.

If RLS is installed then probably it's not in the PATH for the shell from which Kakoune integration tries to start kak-lsp server, the shell which Kakoune uses for `%sh` expansion (it's usually `/bin/sh` I guess). One option is to fix PATH for that shell, and another one is to just copy default `kak-lsp.toml` to `~/.config/kak-lsp/` and edit it replacing `rls` with full path to the binary.

**Comment by atomrc** [comment]
Hey @ul 

Thanks a lot for your fast reply.
Indeed, for some reason, the binary was not reachable by kakoune. (setting the absolute path in `kak-lsp.toml` worked).

I am not sure why, because my user has it in the `PATH`. (I can type `rls` and it just works).
If you have any tips, I'd be glad to hear it.

Thanks again.

**Comment by ul** [comment]
My guess is that shell invoked by Kakounes `%sh` expansion is different from the one you run in terminal and for somewhat reason rustup didn't update the former one's PATH.
