### ISSUE TITLE
Simplify dispatching

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#110]
Ref https://github.com/ul/kak-lsp/commit/3f121aff1259428874fb17a1014cc54e40b39c72#r30889210

**Comment by ricochet1k** [comment]
I'm working on a big refactor based on this idea and a few others I've come across in the process, just FYI.

**Comment by ul** [comment]
Amazing news! Just be aware of https://github.com/ul/kak-lsp/tree/better-character-offset-handling branch. You might want to base your work on it to avoid major conflict as I hope to get this branch into the master soon.

**Comment by ricochet1k** [comment]
Turns out, I will not be able to submit any pull requests, due to the Unlicense and copyright assignment restrictions, because I work for Google. https://opensource.google.com/docs/patching/#forbidden

If you want to switch to a more traditional open source license, such as Apache 2 or MIT like most Rust projects, then I would be able to help. There is more information about licenses here: https://opensource.google.com/docs/using/license/

**Comment by Delapouite** [comment]
Does this license restriction also applies when you make a personal contribution from home on Sundays?

**Comment by ricochet1k** [comment]
Yes it does. As part of my condition of employment, Google owns copyright of all code I write. You can see a hint of that here: https://opensource.google.com/docs/iarc/

**Comment by alexherbo2** [comment]
_All your base are belong to us._

**Comment by ricochet1k** [comment]
I'm applying for an exception. It will take a few weeks to hear back, but they might grant me a copyright release.

**Comment by ul** [comment]
The primary objective of choosing Unlicense was to support Kakoune's model and to remove all obstacles in the community's way. Ironically, it constrained contribution.

I personally am not attached to the Unlicense or any other Public Domain license because I intend to liberate kak-lsp effectively, not formally. If it requires switching to a license which sounds less free, but pragmatically gives more freedom, I'm okay with it.

However, I'd like to hear the opinion of other people as kak-lsp is already a kind of _res publica_, and people who spent their time coding, discussing and using kak-lsp may have ideas about licensing they see the most resonating with the project.

**Comment by ul** [comment]
@ricochet1k how do you think, would dual-licensing under Unlicense/MIT do? There is even a precedent in a Rust ecosystem: https://github.com/docopt/docopt.rs/commit/11b5ff3d3939b7d4ba0e09e457f802a37bb5c5dc

**Comment by ul** [comment]
done: 55dfc83409b9b7d3556bacda8ef8b71fc33b58cd

**Comment by robertmeta** [comment]
https://github.com/gohugoio/hugo/issues/201 -- the same issues took years to fix, lots of great comments in that thread about the issues and legal wrangling.  I am not certain dual-licensing is a complete win because it isn't well understood (so lawyers might still need to be involved).

Is the intention of the dual licensing that each individual chooses the license they support, or must they support both, and when they contribute to they have to flag which one they are contributing under?  I honestly don't know how this is intended to work.

**Comment by ul** [comment]
AFAIK, dual-licensing allows you to choose either license, and considered valid even if licenses contradict each other.

**Comment by robertmeta** [comment]
https://en.wikipedia.org/wiki/Multi-licensing implies it can be either:

> but the simple presence of multiple licenses in a software package or library does not necessarily indicate that the recipient can freely choose one or the other. 

Maybe that needs to be made entirely clear?

**Comment by ul** [comment]
There is already some disambiguation in https://github.com/ul/kak-lsp/blob/master/COPYING
I'm keen to change it if you think it's not clear enough.

**Comment by mawww** [comment]
@ricochet1k I dont see the Unlicense in the list of forbidden licenses, is there another place that shows unlicense is forbidden for google employees ?

**Comment by andreyorst** [comment]
> @ricochet1k I dont see the Unlicense in the list of forbidden licenses, is there another place that shows unlicense is forbidden for google employees ?

Perhaps this paragraph:

> ### Other licenses not listed
> If a license is not listed above in this section, then it requires approval from emailremoved@ (for example by adding emailremoved@ to the R= line of the CL). This approval is required for each usage of the license at Google; you cannot assume that just because an unlisted license was approved for one usage that it is automatically approved for all other usages.

**Comment by nonumeros** [comment]
>Perhaps this paragraph:

nope

more like https://opensource.google.com/docs/thirdparty/licenses/#unencumbered

**Comment by ricochet1k** [comment]
@mawww What @nonumeros listed is correct, and that section is probably going to change soon to explicitly list Unlicense.

@ul IANAL, but licensing is complicated. Dual-license has always meant to me that users of the project as a library can choose between one or the other (though wikipedia says this isn't the case), but that Contributors must license their code using *both* of the licenses to continue to allow users to choose either. Since Unlicense requires copyright assignment, it would still prevent me from contributing at will. I don't understand how the clauses at the beginning of COPYING and CONTRIBUTING can coexist. It's like saying `U & M` == `U | M`.

That being said, I just got notice today that my request for a copyright waiver has been granted, so I'm free to contribute now.

**Comment by ul** [comment]
Yes, unfortunately, it seems that dual-licensing doesn't resolve contribution issue. However, I'm going to keep it just in case someone would like to use kak-lsp code in the license-strict environment where having a MIT option could unblock them.

**Comment by nonumeros** [comment]
>Yes, unfortunately, it seems that dual-licensing doesn't resolve contribution issue. 

Consult a lawyer but that's not what I understand under the current issue . See https://opensource.google.com/docs/thirdparty/licenses/#same

>Since Unlicense requires copyright assignment, it would still prevent me from contributing at will

can't follow you. But then again, consult a lawyer 

See https://unlicense.org/#unlicensing-contributions

      MIT

     The above copyright notice and this permission notice shall be included in all
     copies or substantial portions of the Software.

that seems like an assignment

     Unlicense

     In jurisdictions that recognize copyright laws, the author or authors
     of this software dedicate any and all copyright interest in the
     software to the public domain. We make this dedication for the benefit
     of the public at large and to the detriment of our heirs and
     successors. We intend this dedication to be an overt act of
     relinquishment in perpetuity of all present and future rights to this
     software under copyright law.

non-assignment

**Comment by hacktivista** [comment]
I think MIT-0 is intended for the same use as Unlicense, and used (indeed created) by Amazon, probably Google would not have a problem with it :)

**Comment by ul** [comment]
Closing as related PR is merged.
