### ISSUE TITLE
Question: describe the purpose of systemd service

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#116]
Hi, I noticed that a systemd service exists for kak-lsp, but I don't see any mention of it in the README. Could you describe it a bit? Is it to have one instance of kak-lsp process instead of many? Is is preferred or not? This will also use TCP connected instead of Unix socket, will it be slower? What is its purpose then?

**Comment by ul** [comment]
Both service and TCP mode exist mostly for historical reasons, but I keep them because someone could find them more convenient for their use-case. 

TCP mode was the only transport available and service was the only way to restart kak-lsp server after crash in the earliest versions of kak-lsp. See #36 for details why unix mode became the default and preferred one.

I didn't notice that TCP mode is slower, but I didn't take measurements, it's just a subjective feeling.

You can have one instance of kak-lsp with unix sockets mode as well by using the same name of kak-lsp session for all Kakoune sessions: put `eval %sh{kak-lsp --kakoune -s my-kak-lsp-singleton}` in kakrc instead of default integration and put `lsp-stop-on-exit-disable` right after it.

Single kak-lsp process is totally capable of handling any number of Kakoune sessions. Is it preferred or not, I can't say for sure.

**Comment by maximbaz** [comment]
Thanks 😉
