### ISSUE TITLE
Proper structure of main script, for loading by plugin managers

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#117]
Hello. I'm writing a [plugin manager](https://github.com/andreyorst/plug.kak), and currently I'm not able to use your plugin, if it is loaded by the plugin manager.

I've added `noload` option to workaround this issue, but I think that this isn't proper way of how plugin should work. I still want to be able to start lsp manually, I just don't want to avoid loading of main script, and load it via shell command.

My current setup is:

```kak
plug "ul/kak-lsp" "noload" %{
    hook global WinSetOption filetype=(c,cpp,rust) %{
        evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
    }
}
```

Let me breakdown this for you:
`plug` - it's a command that does the following:
- checks if first parameter (which is a repo) exists at plugin installation path, and if it exists:
  - parses parameters, like `"noload"`, `"branch: ..."`, `"tag: ..."`;
  - loads all `.kak` files in the repo. If `"noload"` is specified this step is skipped;
  - loads `%{settings}` from the last parameter even if previous step was skipped.

So this configuration skips the plugin files itself, but sets the hooks that will call external program, that will load `lsp.kak` script. I think that this should be handled by `lsp.kak` and not by external program.  So user configuration can be like this:

```kak
plug "ul/kak-lsp" %{
    set-option global lsp_path_to_executable "no/more/symlinking"
    hook global WinSetOption filetype=(c,cpp,rust) %{
        lsp-start [optional parameters]
    }
}
```

So script could handle everything by itself, as a plugin should do. Final proposal workflow is:

- `source lsp.kak` either by plugin manager, or from user configuration, or from autoload folder;
- configure some options like path to kak-lsp inside kakoune's config;
- start lsp via generic command by entering it manually or by hook.

I understand that simply calling `kak-lsp` from shell and passing session id to it feels easier, but I think that this should be handled in the main script, and not in the binary.

**Comment by ul** [comment]
You are right, for now there is no strict need for `lsp.kak` to be a template rather than proper kak script. It was made that way for simpler, quicker, less error prone integration as `kak-lsp --kakoune` output is always up-to-date with kak-lsp version you run, with additional arguments you pass to it and also is future proof in case script will become complex enough that parts of it will be generated or heavily altered based on configuration.

And because Kakoune scripts heavily use `%sh` expansion, I don't see big difference in running

```
set-option global lsp_path_to_executable "no/more/symlinking"
evaluate-commands %sh{ $kak_opt_lsp_path_to_executable --kakoune -s $kak_session }
```

vs

```
set-option global lsp_path_to_executable "no/more/symlinking"
source lsp.kak
lsp-start [optional parameters]
```

because you have no guarantees about what `source lsp.kak` or `lsp-start` is doing, it could be that it's executing the same `evaluate-commands %sh{ ... }`

The only real problem which I see with current `lsp.kak` is that it sets global hooks in `lsp-enable` (and executes `lsp-enable` automatically) so you can't easily enable lsp only for filetypes you want (it's completely doable, but requires more manual work). But this is unrelated to the way you obtain `lsp.kak`, as a plain file or output of `kak-lsp --kakoune`

I wonder what other people think about it.

**Comment by maximbaz** [comment]
Having kak-lsp executable in sync with lsp.kak is quite important, @andreyorst since plug.kak is supposed to take care of updates, can/will it be able to recompile kak-lsp binary?

For package maintainers (me for `AUR/kak-lsp` and @GordStephen for `AUR/kak-lsp-git`) who take care of compiling binaries, we just need to agree to put the corresponding `lsp.kak` in some place (e.g. `/usr/share/kak-lsp/lsp.kak`) so people always source the appropriate lsp.kak that matches the binary.

**Comment by andreyorst** [comment]
> Having kak-lsp executable in sync with lsp.kak is quite important, @andreyorst since plug.kak is supposed to take care of updates, can/will it be able to recompile kak-lsp binary?

yes, im working on it in post_update_hooks branch. It already does it, just need more polishing.

**Comment by andreyorst** [comment]
> And because Kakoune scripts heavily use %sh expansion, I don't see big difference in running

It's just isolation of plugin guts into friendly user interface. 

> because you have no guarantees about what source lsp.kak or lsp-start is doing, it could be that it's executing the same evaluate-commands %sh{ ... }

that's the point. the plugin should do all that work. User simply executes the command.

> The only real problem which I see with current lsp.kak is that it sets global hooks in lsp-enable (and executes lsp-enable automatically) so you can't easily enable lsp only for filetypes you want (it's completely doable, but requires more manual work). But this is unrelated to the way you obtain lsp.kak, as a plain file or output of kak-lsp --kakoune

There's another way of solving the problem with the script being loaded by external tool, and not by plugin manager. It is [standardization of plugin file-structure layout](https://github.com/mawww/kakoune/issues/2402). Especially this comment: https://github.com/mawww/kakoune/issues/2402#issuecomment-426759781, which says that there should be a folder which isn't directly loaded by plugin manager, or Kakoune, but loaded by main script when it is needed to be loaded, much like in case of your plugin. So you'll have a main script that defines user interface, and a script that is being sourced with kak-lsp, called from main script, with comprehend user interface.

**Comment by ul** [comment]
Sounds like a good idea. PR is welcome, or eventually I'll get to it by myself (but I'm inclined to prioritize few other issues before it for myself).

**Comment by andreyorst** [comment]
I too need to finish some things with my plug.kak, then I'll try to do something about it. Something not right with post update hooks right now

**Comment by andreyorst** [comment]
@dpc, I'm using kak-lsp with plug kak. Here's the configuration snippet:
```kak
plug "ul/kak-lsp" noload do %{cargo build --release} %{
    hook global WinSetOption filetype=(c|cpp|rust) %{
        evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
    }
}
```

**Comment by dpc** [comment]
Why do I keep getting `evaluate-commands` errors? It seems it's not a proper command. :/

**Comment by dpc** [comment]
Other than some hacks for version detection, it seems to start now. Thank you @andreyorst .

Is there any need to also shut-down `kak-lsp` etc? It seems that typically in kak when one enables something in some form of "enter"-hook, it had to be disabled in "exit"-hook.

I also wasn't able to get `gd`/`:lsp-definition` to work. It doesn't seem to do anything. But I guess that's a topic of another issue.

**Comment by dpc** [comment]
@andreyorst It looks like this way to start doesn't fully work. See https://github.com/ul/kak-lsp/issues/129#issuecomment-440471386

**Comment by ul** [comment]
I pushed `plugin.kak` file which serves an experimental playground for `plug.kak`-style integration. As soon as it gets into a good shape I'm going to merge it with `lsp.kak`.

That how I use it in my `kakrc`:

```
plug "ul/kak-lsp" do %{cargo build --release} load %{plugin.kak} %{
    set global lsp_diagnostic_line_error_sign '▓'
    set global lsp_diagnostic_line_warning_sign '▒'

    map global lsp N '<esc>: lsp-find-error --include-warnings<ret>'             -docstring 'find next error/warning'
    map global lsp P '<esc>: lsp-find-error --include-warnings --previous<ret>'  -docstring 'find previous error/warning'

    hook global WinSetOption filetype=(rust|python|go|javascript) %{
        set window lsp_hover_anchor true
        set -add window modelinefmt ' err:%opt{lsp_diagnostic_count}'
        lsp-enable-window
    }

    hook global WinSetOption filetype=(rust|python|go) %{
        set window lsp_auto_highlight_references true
        hook window BufWritePre .* %{
            lsp-formatting-sync
        }
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"
    }

    hook global KakEnd .* lsp-exit
}
```

**Comment by ul** [comment]
Taking in account #129 now I'm pretty sure that the root of the problem is that kak-lsp fails to start server in your environment. And taking in account that manually it starts well I think there could be a problem in how `daemonize` library works on your system. When kak-lsp starts server automatically it tries to detach it using that library. Try to run manually kak-lsp with `--daemonize` flag and look if it fails. You also need to specify session, like `kak-lsp -s foo --daemonize`

**Comment by andreyorst** [comment]
> I pushed `plugin.kak` file which serves an experimental playground for `plug.kak`-style integration. As soon as it gets into a good shape I'm going to merge it with `lsp.kak`

Cool, I'll test it. However name `plugin.kak` some kind weird to me. I like to name scripts conventionally to the plugin name, so maybe `lsp-loader.kak` would be better?

**Comment by ul** [comment]
I don't mind renaming it. It's just a temporary name for proof of concept.

**Comment by dpc** [comment]
@ul When I test it manually, it seems to work. I do get a daemonized process. However when I use your snippet, I don't get any `kak-lsp` process in `ps fax` output, so it is not starting correctly.

Investigating more...

**Comment by dpc** [comment]
@ul It looks like it's not attempted to be started. What exactly in your snippet is supposed to start kak-lsp?

**Comment by dpc** [comment]
When I do `:echo %sh{ echo ${kak_opt_lsp_cmd} } ` I get the path to my project's directory, not to the plugin directory. Could it be you've tested it on `kak-lsp` source code so it worked for you @ul? :D

**Comment by ul** [comment]
Lol, I assumed that `plug.kak` runs config block in plugins directory. Meanwhile you can `set global lsp_cmd /absolute/path/to/kak-lsp` manually in config block.

**Comment by dpc** [comment]
@ul Still no joy. I have a wrapper in the original place that logs on start and exit and starts the original binary:

```
--request
--request
--request
--request
Finished with 0
Finished with 0
Finished with 0
--request
--request
Finished with 0
Finished with 0
--request
Finished with 0
--request
--request
Finished with 0

--request
--request
Finished with 0
Finished with 0
Finished with 0
```

**Comment by andreyorst** [comment]
> Lol, I assumed that `plug.kak` runs config block in plugins directory. Meanwhile you can `set global lsp_cmd /absolute/path/to/kak-lsp` manually in config block.

No, there was no reason to run configuration block in plugin directory, since all configurations are usually just `set-option`s, `map`s and `hook`s. Post-update hooks are executed in plugin directory, since we need to call plugin file structure aware commands. If it is necessary I can make configurations in plugin directory too, that should not break anything.

**Comment by ul** [comment]
>  If it is necessary I can make configurations in plugin directory too, that should not break anything.

I think that `decl str lsp_cmd "%opt{plug_install_dir}/kak-lsp/target/release/kak-lsp"` should mostly work, so probably no need to add changing directory to plugins. It was just my assumption which I didn't validate and made mistake because of it.

**Comment by ul** [comment]
Anyway, user can override `lsp_cmd` manually. But I think that using plug.kak implies that user isn't required to hardcode paths to plugin files or care about putting them into PATH.

**Comment by dpc** [comment]
@andreyorst I don't want to be setting it manually if I'm using `plug.kak`! Hindrance! :D

**Comment by dpc** [comment]
It's not impossible to give the user the convenience of not having to worry about anything, and just get the binary compiled, automatically updated and recompiled with `:plug-install` etc. The plugin should take care of itself as much as possible.

I would say the whole config should be:

```
plug "ul/kak-lsp" %{
    hook global WinSetOption filetype=(c,cpp,rust) %{
        lsp-start [optional parameters]
    }
}
```

and that's it. Users can set `lsp_path_to_executable` if they want to, or are not using `plug.kak`.

**Comment by dpc** [comment]
Bah. Maybe even just 

```
plug "ul/kak-lsp"
```

since `kak-lsp` does already know which languages it supports, so it can turn itself on automatically for these languages (with an option to disable it or something).

**Comment by andreyorst** [comment]
> The plugin should take care of itself as much as possible.

Yes, that's the point of this ticket, however since there's no standard layout of how plugins are structured, or installed, or anything else, we can't rely on certain way.

**Comment by dpc** [comment]
@andreyorst as an author of `plug.kak` you have a historical opportunity to design such layout, and then enforce it with your iron fist on all the plugins that want to be installable with `plug.kak`.

**Comment by andreyorst** [comment]
I've thought of it, but I think that I can't do that just by me, since needs may differ, and such layout can actually make developing plugins more difficult. That is, the layout should be structured by community of plugin makers and adopted by managers.

@dpc This went too far off topic. If you have any ideas or want to discuss existing ones, you're welcome to https://github.com/mawww/kakoune/issues/2402

**Comment by dpc** [comment]
> I've thought of it, but I think that I can't do that just by me, since needs may differ, and such layout can actually make developing plugins more difficult. 

@andreyorst Most of plugins should work as is. Just load everything. For fancy ones like `kak-lsp`, just introduce some magic file that means "this is an advanced plugin that requires special care", and make it so that there has to be some form of a `plugin_api_version = 0` in that file.

Make up your own API, which you think is best according to your current knowledge. You can use `kak-lsp` as one of the first cases. After you gather more experience and input, you can do another design of your API. Packages that will want to use it will just have to set `plugin_api_version = 1`. In `plug.kak` you can detect the version of support old API(s) and new ones for as long as you see reasonable, displaying a warning when a plugin is using an old API version.


In software design iteration times trumps everything. I prefer "do it, test it in real world, get feedback, improve" approach that endlessly debating between many people what to do. As long as you open yourself a way to introduce new versions without breaking the whole ecosystem (version flag), it's going to be OK.

I highly recommend "Antifragile" by Nassim Taleb for more in depth story why fast incremental feedback-based approach always produces better results than top-down design.
