### ISSUE TITLE
`gd` doesn't work and I don't why

### ISSUE THREAD

**Issue by dpc** [ul/kak-lsp#129]
It just doesn't jump anywhere.

**Comment by ul** [comment]
Hello! Thank you for the report. Would you mind providing a bit more context: what's your environment, language server, Kakoune's `*debug*` buffer content, kak-lsp logs (please refer https://github.com/ul/kak-lsp/#troubleshooting for a one of the ways to obtain them).

**Comment by dpc** [comment]
So I did that:

```
plug "ul/kak-lsp" noload do %{cargo build --release} %{
	hook global WinSetOption filetype=(c|cpp|rust) %{
		evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
		nop %sh{ (kak-lsp -s $kak_session -vvv ) > /tmp/kak-lsp.log 2>&1 < /dev/null & }

		set-option global lsp_server_configuration rust.clippy_preference="on"
		set-option global lsp_auto_highlight_references true
		set-option global lsp_hover_anchor false
		lsp-auto-hover-enable
	}

    hook global WinSetOption filetype=rust %{
    	hook window BufWritePre .* lsp-formatting-sync
    }
}
```

when I start `kak` I get:

`*debug*`


```
*** This is the debug buffer, where debug info will be written ***
Dependency unmet: jq, please install it to use go-tools
loaded plug.kak (configuration) in 0.01 seconds
loaded fzf.kak in 0.01 seconds
loaded kak-lsp (configuration) in 0.01 seconds
loaded parinfer-rust in 0.01 seconds
loaded kakoune-gdb in 0.01 seconds
loaded smarttab.kak in 0.01 seconds
loaded kakoune-number-toggle in 0.01 seconds
loaded kakoune-cargo in 0.01 seconds
Config-change detected: rust.clippy_preference="on"
kak-lsp: Language server is not initialized, parking request
```


https://pastebin.com/xZtMNiCu

with this looking imediately suspicious:

```
, module: kak_lsp::editor_transport:151
Nov 20 13:58:46.021 DEBG Language server is not configured for extension `log`, module: kak_lsp::session:102
```

**Comment by dpc** [comment]
When I do `gd` nothing interesting happens in the log. Maybe `gd` is taken over by something else?

**Comment by dpc** [comment]
I updated all the rust things, and now it works. So it was me. Sorry.

It's all glorious. Thank you so much! Rust experience in Kakoune is better than in Vim now.

**Comment by dpc** [comment]
Actually, it looks like the debug command fixed it!

```
		evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
		nop %sh{ (kak-lsp -s $kak_session -vvv ) > /tmp/kak-lsp.log 2>&1 < /dev/null & }
```

So it looks like my original invocation was wrong?

**Comment by dpc** [comment]
So what is the right way to start lsp server? Why is the `README.md` say `--kakoune` argument should be there, but in the debug mode I don't pass it there? I don't get it.

**Comment by dpc** [comment]
I think it has something to do with `plug.vim`, and I was unable to get the right combination. It either doesn't fully work, or blocks on start. Only if I start both lines everything works.

So I'm just going to run with both for now... :D

**Comment by ul** [comment]
> So what is the right way to start lsp server? Why is the README.md say --kakoune argument should be there, but in the debug mode I don't pass it there? I don't get it.

`--kakoune` argument tells kak-lsp to return Kakoune script which provides default integration. When this argument is passed kak-lsp spits out `lsp.kak` contents with `lsp_cmd` template filled in and exits. And only when the first request is sent, it tries to spin up kak-lsp server. Debug command starts that server explicitly. It's totally okay to keep it, you just might want to remove `-vvv` argument for daily use to not litter your disk with logs.

Using kak-lsp via `plug.kak` as you did has 2 caveats:

* `kak-lsp --kakoune` output executes `lsp-enable` which sets global hooks. If I understand correctly, in your setup it leads to multiple requests fired on the same event (because `lsp-enable` is executed each time you open Rust file and multiple identical hooks are set), and they could interfere with each other. It's easy to fix, but it's breaking change and I'm waiting while it would be clear what other changes are required to make kak-lsp work with `plug.kak` to make them in one go. Meanwhile, you might want to move `evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }` from hook like this:

```
plug "ul/kak-lsp" noload do %{cargo build --release} %{
    evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
    
    hook global WinSetOption filetype=(c|cpp|rust) %{
        nop %sh{ kak-lsp -s $kak_session }
        set-option global lsp_server_configuration rust.clippy_preference="on"
        set-option global lsp_auto_highlight_references true
        set-option global lsp_hover_anchor false
        lsp-auto-hover-enable
    }

    hook global WinSetOption filetype=rust %{
    	hook window BufWritePre .* lsp-formatting-sync
    }
}
```

* Because `plug.kak` builds kak-lsp binary in place it might end up not in your PATH, that's probably why kak-lsp fails to start it's own server.

I see that people started to use `plug.kak` actively, I think I should give it a go by myself and prioritize #117.

**Comment by ul** [comment]
Sorry, the second caveat is not relevant because kak-lsp put full path in `lsp_cmd`. Quite strange why it fails to start the server then.
