### ISSUE TITLE
lsp command defined with -shell-candidates instead of -shell-script-candidates

### ISSUE THREAD

**Issue by alexherbo2** [ul/kak-lsp#148]
Kakoune is compiled from _HEAD_ with version `2018.10.27`.

**Comment by ul** [comment]
It's because [this condition](https://github.com/ul/kak-lsp/blob/master/rc/lsp.kak#L775) assumes `v` prefix before version. Ref #99 thread for a similar problem.

I'm not sure how to make this check robust. Probably I should remove it as time passed and perhaps no one uses Kakoune version which requires `-shell-candidates` anymore.

**Comment by SolitudeSF** [comment]
so, is there shortterm workaround?

**Comment by ul** [comment]
Yes, to workaround it just edit `lsp.kak` and remove version check. Then either rebuild kak-lsp or source `lsp.kak` directly instead of `kak-lsp  --kakoune` invocation.

**Comment by ul** [comment]
I would be grateful for any ideas about how to ensure if it's already safe to remove version check for everyone; or how to make this check more robust.

**Comment by maximbaz** [comment]
I suggest you just keep kak-lsp on par with the latest release of kakoune, I doubt there are people who update kak-lsp but not kakoune, and even if there are, it will be a nice push for them to finally update 😉

**Comment by SolitudeSF** [comment]
yes, just put a hard requirement on kakoune version. `2018.10.27` is already in all repos that matter.
