### ISSUE TITLE
Usage outside of kakoune

### ISSUE THREAD

**Issue by jacobdufault** [ul/kak-lsp#15]
I'm wondering if it is possible to use kak-lsp outside of kakoune? I'd like to have a language server command-line client that I can use to test [cquery](https://github.com/cquery-project/cquery). So far I've been working on my own solution, but it'd be a good idea not to duplicate the effort.

I need to browse the implementation more carefully, but I think cquery e2e testing has a few requirements:

- send a message to the language server, wait for a reply
- send an arbitrary (ie, not hard-coded in kak-lsp) message and wait for a reply
- specify initialization options in the init message (though this can be worked around)

Any thoughts? If you're not interested in usage outside of kakoune that's completely okay :)

**Comment by ul** [comment]
I'm not opposed to adding those capabilities (it definitely legit use-case and implementation of it will require architectural improvements in kak-lsp which will pay back later many times). I have only two concerns related mostly to resource availability:

1. I found myself personally quite short of time these days, thus when spending time on kak-lsp I naturally going to focus on its primary feature set.
2. If you are looking just for sending and receiving arbitrary messages to language server then probably rolling up ad hoc solution around any convenient jsonrpc client could be much more efficient investment for you. If you are looking for emulation of entire editor interaction lifecycle then building on top of kak-lsp might worth efforts because it maintains some bits of state and have some extra logic on top of just forwarding messages which could be tedious to re-implement especially when we'll get support for more LSP features.

That's said, I'm more than happy to add support for more generic usage to roadmap and to accept PR's with its implementation (and I hope eventually participate). If you are interested I can go into details of how kak-lsp is structured at the moment and what is most probable have to be changed to fulfill requirements you listed.

**Comment by ul** [comment]
I'm going to close this issue due to inactivity. Feel free to re-open at any time to propose the next step in making kak-lsp more suitable to your needs.
