### ISSUE TITLE
How to ignore optional fields in custom LSP server responses

### ISSUE THREAD

**Issue by vnagarnaik** [ul/kak-lsp#173]
I am using a custom LSP server implementation at work which adds extra fields to responses such as textDocument/completion that are not part of LSP protocol. These extra fields are used for a custom client implementation. However, using this server with kak-lsp causes panic:

>thread '<unnamed\>' panicked at 'Failed to parse completion response: Error("data did not match any variant of untagged enum CompletionResponse", line: 0, column: 0)', libcore/result.
rs:1009:5

 The LSP server works with various open source clients like [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and [Sublime Text 3](https://github.com/tomv564/LSP). Probably these clients ignore the additional fields and parse only the known JSON fields.

Is there a way to use kak-lsp with such a server implementation? I could maintain a private version of kak-lsp but I won't really relish it.

**Comment by ul** [comment]
kak-lsp relies on lsp_types and serde for deserialization of responses. Ideal solution would be to handle extra fields on lsp_types side as otherwise we will need to re-implement response types in kak-lsp. I'm not sure how exactly to relax serde for struct-inside-enum deserialization, but I guess it could be done, and most likely it should be done at the time of type declaration.

**Comment by ul** [comment]
Closing this issue based on discussion in https://github.com/gluon-lang/lsp-types/issues/101
