### ISSUE TITLE
Does not work on multi-user setup

### ISSUE THREAD

**Issue by SirAiedail** [ul/kak-lsp#174]
When I try to start kakoune sessions with two different users, `kak-lsp` doesn't work for the second one (or subsequent ones). Additionally, insert mode in the second session has very high input lag.
It works, if I delete `/tmp/kak-lsp` before starting the second session, but that breaks the first session if it's still running, or if the second user to start kakoune is `root`.

**Steps to reproduce:**
1. `kakrc`:
```
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
```
2. Start kakoune as `root` with above settings
3. Start kakoune as regular user with above settings

**Versions:**
Kakoune: `v2018.10.27-163-ga7c80f38`
kak-lsp: `6.1.0` (built from `aur/kak-lsp-git`)

**Comment by ul** [comment]
Good catch! It's most likely because of permissions set to kak-lsp's temp directory: https://github.com/ul/kak-lsp/blob/a64a8b2d20854d1b91058c770dc83441df1fd1d7/src/util.rs#L17

I think they could be relaxed as long as permissions on individual sockets / temporary files are correctly set. I don't think the ability to list other user's sessions is the security vulnerability in this case (though we can go for using hashes instead of plain session names if this is an issue).

**Comment by ul** [comment]
I think I now fairly replicated Kakoune's behaviour in that regard by having per-user sub-dirs. However, you most likely need to remove existing `/tmp/kak-lsp` to make it work. Please let me know if you hit any issues with the new approach.

**Comment by SirAiedail** [comment]
It seems that the directory creation is subject to umask, since it's created with `0755` permissions on my machine (with umask `022`) even though `0777` is specified in the source.
Because of that processes of other users still can't write to their temp directory.
