### ISSUE TITLE
go formatting buggy

### ISSUE THREAD

**Issue by dgrisham** [ul/kak-lsp#188]
With the following entry in `kak-lsp.toml`:

```
[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "bingo"
```

and the following file:

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, world!")
}
```

(Note that the spacing before the `fmt.Println()` call is **4 spaces**, not a tab character.)

Running `lsp-formatting` on this file results in:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, world!")
```

Now the spacing before `fmt.Println()` is a tab character, but the closing brace is missing.

If I have two print statements, like so (again with 4 spaces before each print):

```go
package main

import "fmt"

func main() {
    fmt.Println("first");
    fmt.Println("second");
}
```

The result of `lsp-formatting` is:

```go
package main

import "fmt"

func main() {
	fmt.Println("first")	fmt.Println("second")

```

Again, the spacing before *each* `fmt.Println()` call is a tab, but the newline between them and the closing brace are missing. The tabs are expected, but the missing characters are obviously not. This happens whether `bingo` is set to use `goimports` or `gofmt`, which I do by adding one of the following lines to the `[language.go]` entry in `kak-lsp.toml`:

```
# for goimports
args = ["--format-style", "goimports"]
# for gofmt
args = ["--format-style", "gofmt"]
```

Since it seems to happen with either formatting tool, the issue is more likely to be with `kak-lsp` or `bingo` itself. The [last time I experienced something like this](https://github.com/ul/kak-lsp/issues/112) turned out to be a `kak-lsp` issue, so I thought I'd post this here.

**Comment by ul** [comment]
I failed to investigate this issue right now because `bingo` gives me "package is null for file main.go" and its successor `gopls` just stops responding after initialization (not sure if its kak-lsp or gopls fault). I will try again later. Meanwhile, if any of Go users are reading it I'd appreciate their comments.

**Comment by maximbaz** [comment]
@ul run `go mod init temp` in the folder where you created the go file.

**Comment by dgrisham** [comment]
@maximbaz nice, thanks for that! Good fix for now. Out of curiosity (and also because it relates to how I config `kak-lsp`), is there any particular reason you use `BufWritePost` instead of `BufWritePre` here? Do you just prefer to save exactly what you see, instead running the formatter just before saving?

**Comment by ul** [comment]
@maximbaz thanks, now I'm able to reproduce it, will investigate the root cause this weekend.

**Comment by maximbaz** [comment]
@dgrisham that's because `goimports` operates on a file, not on stdin, so I have to first save the file, then tell `goimports` to go and format that file, and then I run `edit!` which reloads the (now modified) file back into kakoune window.

For other formatters, which can operate on stdin directly, these hacks are not needed and we can use `formatcmd` option directly, for example:

```
set-option buffer formatcmd "prettier --stdin-filepath=${kak_buffile}"
```
