### ISSUE TITLE
Breaking change in config file location

### ISSUE THREAD

**Issue by keeslinp** [ul/kak-lsp#216]
By updating to respect XDG_CONFIG_HOME, you made it so that macos does not look under .config anymore. It took my a while to figure out why my configs stopped working after updating.

Here is the relevant doc:
https://docs.rs/dirs/2.0.1/dirs/fn.config_dir.html

Might be worthwhile to at least clarify that in the readme.

**Comment by ul** [comment]
Thank you for catching this problem (and apologies for introducing it!), I totally missed it even though I use kak-lsp on macOs (didn't read docs attentively and my pattern of usage is different because of development: I have all my customizations sitting in the repo's kak-lsp.toml usually and rebuild kak-lsp frequently so it gets embedded).

I will update docs and make release clear about the breaking change.
