### ISSUE TITLE
lsp-find-error: DiagnosticError is not a number

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#324]
Following error keeps popping up while invoking `lsp-find-error`:

```
Error: 1:1: 'lsp-find-error' 2:5: 'evaluate-commands' 1:1: 'edit' 17+0|DiagnosticError is not a number
```

Following file may help to reproduce, it's where I got this error.
```rust
pub struct StrSplit {}

impl StrSplit {
    pub fn new(haystack: &str, delimiter: &str) -> Self {}
}

impl Iterator for StrSplit {
    type Item = &str;
    fn next(&mut self) -> Option<Self::Item> {}
}
```

**Comment by tadeokondrak** [comment]
Hmm, this probably comes from my change here: https://github.com/ul/kak-lsp/commit/3dbb2936061d6158cc30e60ff2b08d6b8e925005#diff-dfd26227c4842bd3288e9b1f53f0089fR188, because somehow https://github.com/ul/kak-lsp/blob/c77f1133d9eeb3b005087ac13a1ad9f590ff824d/src/position.rs#L109 is producing zero-width ranges, which it shouldn't.

**Comment by vbauerster** [comment]
I think it's related.
Hook `hook window BufWritePre .* lsp-formatting-sync` causing following error:
```
error running hook BufWritePre(/Users/vbauer/go/src/github.com/vbauerster/mpb/progress.go)/: 1:1: 'lsp-formatting-sync' 2:5: 'lsp-did-change-and-then' 1:2: 'try' 2:5: 'evaluate-commands' 1:1: 'lsp-formatting-sync-request' 2:5: 'evaluate-commands' 1:1: 'eval' 1:1: 'select' '71.1+0' does not follow <line>.<column>,<line>.<column> format
```
