### ISSUE TITLE
Frequent errors when moving

### ISSUE THREAD

**Issue by sebsebmc** [ul/kak-lsp#43]
I'm getting really frequent crashes when using kak-lsp and simply moving around in a file.

Here is a dump of a typical crash with full verbosity and RUST_BACKTRACE=1. I don't know any Rust so I can't be much help here, but it feels like a race condition of some sort.

https://pastebin.com/Qj8TL2dG

I'm using kak-lsp 3.1.3 on WSL and the only language server I have installed is https://github.com/sourcegraph/go-langserver

**Comment by ul** [comment]
Thank you for report! Looks like the following happens:

1. On each move textDocument/hover request is sent to kak-lsp and forwarded to go-langserver (this behaviour was made configurable in [v3.2.0](https://github.com/ul/kak-lsp/releases/tag/v3.2.0))
2. go-langserver responds with `{"id":6,"result":{"contents":null},"jsonrpc":"2.0"}` which doesn't comply to [spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover) (expected response for this case is either `{"id":6,"result":null,"jsonrpc":"2.0"}` or `{"id":6,"result":{"contents":[]},"jsonrpc":"2.0"}` or `{"id":6,"result":{"contents":""},"jsonrpc":"2.0"}`
3. Response validation fails and kak-lsp panics because error-handling is not thought out well yet (situation was improved a bit in [v3.3.1](https://github.com/ul/kak-lsp/releases/tag/v3.3.1))

I think it worth posting bug to go-langserver to fix response. Meanwhile I can add support for that kind of malformed response.

**Comment by ul** [comment]
I installed go-langserver via `go get -u github.com/sourcegraph/go-langserver` and tested it with its own repo. It seems sending proper response. Would you mind updating go-langserver and trying again?

**Comment by ul** [comment]
Ah, no, I caught it!

**Comment by ul** [comment]
Let's wait for response from go-langserver authors https://github.com/sourcegraph/go-langserver/issues/284

If they will say that it won't be fixed in the nearest future then I'll push commit to support malformed response.

**Comment by ul** [comment]
Closing it because bug in go-langserver was fixed.
