### ISSUE TITLE
[Feature request] Function signature hint

### ISSUE THREAD

**Issue by sasdf** [ul/kak-lsp#59]
Language server can provide parameter names and documents while typing parameters, see [signatureHelper](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp).

#### Context with cursor at position 3
```python
bin(
```
#### Response
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "signatures": [
      {
        "label": "Return the binary representation of an integer.",
        "documentation": "Return the binary representation of an integer.\n\n>>> bin(2796202)\n0b1010101010101010101010",
        "parameters": [
          {
            "label": "number",
            "documentation": null
          }
        ]
      }
    ],
    "activeSignature": 0,
    "activeParameter": 0
  }
}
```

**Comment by sasdf** [comment]
Using `echo` to show signature will be better than `info`. Info window will be closed when auto-completion menu changed. while messages in status bar won't.

**Comment by sebsebmc** [comment]
I prefer the anchored version that you get typically from something like IntelliSense. You can get hover info in normal mode displayed in the info box, and as you type in insert mode, you get completions which are augmented with signature help. I'm not sure if you can have both an anchored info box and a completions list visible at the same time.
https://github.com/mawww/kakoune/issues/1260 shows other attempts at this

**Comment by sasdf** [comment]
It seems that info box and docstring in completions list won't be visible at the same time.

You may also want to try `lsp-auto-hover-insert-mode-enable` to see how flickering it is when display in info box, and that's why i prefer the echo version.

**Comment by ul** [comment]
I'm not sure which way is the best by default, but anyway it's easily customizable now. Just override `lsp-show-hover` command in your kakrc to use `echo` instead of `info` when in insert mode. It's signature is `lsp-show-hover line.char content`, so you need to add `echo %arg{2}` as the second branch of condition checking current mode. And after implementing `signatureHelp` we'll get something like `lsp-show-signature-help` so it would be enough to override it without overloading `lsp-show-hover` with mode detection.

**Comment by ul** [comment]
FYI rls doesn't support it yet: https://github.com/rust-lang-nursery/rls/issues/97

**Comment by ul** [comment]
Looks like many server miss it =( Anyway, I will add basic implementation and we will polish it based on feedback.
